dist: xenial
sudo: required

before_install:
  - sudo ./install-dependencies.sh

install:
  - rm -rf public

script:
  - hugo
  - pushd public && htmlproofer . --check-html --disable-external --allow-hash-href --empty-alt-ignore --file-ignore ./js/vendor/reveal.js/plugin/notes/notes.html --url-swap '\/makova_lab/:/' && popd

before_deploy:
  - openssl aes-256-cbc -K $encrypted_bb416c079b5b_key -iv $encrypted_bb416c079b5b_iv -in deploy_ssh.enc -out deploy_ssh -d
  - eval "$( ssh-agent -s )"
  - chmod 600 /tmp/deploy_ssh
  - ssh-add /tmp/deploy_ssh
  - echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --quiet ${TRAVIS_BUILD_DIR}/public/ ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIRECTORY}
  on:
    branch: master

env:
  global:
    - HUGO_RELEASE=0.50
    - secure: IT46O/dqHaZwJO41C1VOAAb8rgGiAlZJMMZQQx9wag78PnackFCs2xZS5OtGauzCG5LgOaabpzU8dDiim+4o5NYnWI2/TdXRuIHHvFMW3AHCmc6b1FFrTbLLRqqOEpAF+F3/xgk1+CeOA92hs//njrKJHlpST+rq35xSoHiAOtaJyB4Ajx88VZBN+n56r+ujNudPI691hFQw6t7KxBu4QnLgvZXG5mhkb4H0IcKtCFiqCP13Mj0D3ouMIy/TiEPZM80ayiyA5kPNrKcFcq08ZyZZkZaKtING7iMXHEWGeDtLsRp411sCg4CvYoqtYlDez9GyaXvY+A1X9JYJVV7ouEX7D+6/WL2lnBrN2z+dZgQTy+9NgddaDvezqEXcntGM6kvbylDuRI1aI1C+EMoJKQfKgBuSFHJEsRKSkQ6cH/v6RhcUrh5+t7nQApj6heghcMU2EM4xCm8HkDUKoOdLGMxMd6INvZOVX87OV2ERlm17+UfUivloynlqg8DAJZcjKprY60LSCWYiHOUX93COzUqSWu9BupZRMVrhGGWLHsaLbJzowLnHrv5m/GcYt7wFI+4AbgiZaqPT1g5Q/ilHx9IM5rzqZlEtG8xE2hm4PrNPBCXRaaEeIjpi5esOEP2/KCMqF84dotw5ztRLEKhS8EQHmuy79hLBr+/IKGVbQ54=
    - secure: S7C+ZNnd9rM/n0dfUTnse3cvXrQoC/VXbvWCxmGcOrR2sZD5DO1FteTqKfMPZ4IIzEYlsDESQ9IW20VkqIabTNMv2o3/NTIG/hK5gzzpo4tQWOu3fY7mAt8XcOuaMPOU6n/pV36MIcwBQ9lLeHn+26+mT3x+OVKgZnquPI58ltOIuIugnnihsifmg0zRSHhCQO4aAC7yjgOr3g/2Q4mQg1wsM+eW42sEItPdpX8jzi67f5zsLUXTQxV8gQeDbltTWzD+8EHEKA7qN6XgU4wAZZ2I9kop9QH4BE70nt4/gQAmXjgQI5MZIQGG04AQTrS1GswCk9sdXP9b+vMR8SQhS9vLH6ku7s2WW5qQSss3Y46eNIaouFNM3mqA9luYpIzHgxd8Ap+gJJNVAtVyAZDGPZuwNOMLlyO5Zcur0loplSo7uiirg7vXIMbZEiNwIf6VtBUD2jnH+ytsaQM8kNPxk+QGkzrkJvarLHowY9ViHvfUNDA0l6BG42Jn8wVYzway0hfTYanNtXHoC9W9f0IZhwNQptv3w8Di5RAwdT66D83r+G98hRNu8IL651/xLPtcV++vFJlYr33U8QCVNuKKiFU9mDFuwvqOaRUf/AP76pauFqIt3NKMqd0Tg92ZEge6n9lttNuaPXSJgidlTnSKAX2ygz9F7eq/DUcpmqqrGS4=
    - secure: N4Sdppl6NGTARnrdnhNnvsUv5hSDURu3vkAVM3cLbteV+hhplOLT5VC+uPdZ/iCjT0KslDE/ztWYq3KmH4dEgg6qjPUuFIJrWlfDJx23zU/Dq3okwZyi8ZFfpVwq7P1Mgcxc72wEpI++uGpRnvMXZUo5TUO9tomAWMQ/kS4djsSDSzRAFNOjR7UqIQPRQi2bDIMhE1zx4vpwl4rrsvPLdhcsPTT0HK7I3geCBkSIis2B9xdaxp/H7BJ0rk/yGsdr/5GOpYquw2j6IX61zAJA/NSnjDHhyxRF/M4DdhQ8GwCyKgGGn1TQRta/yODH2JSkI9d67Iyu7oiACLbhQAq9XOM4AJfU01p7ROJuJOxq1rX9vv3Kzi4s6Hoh5uALLaJwfLwo2dPqHLPd9vQGRmOoAVvCyviU/Ol4lSJJKfxYPzprH7Vyn+IGdZbmpdRxgonCHfzBPJvmfDhhlIy2zp1skElde392TiO8Hhj6/fsyaOScYLmYHi6kQOBgnE3o4EoLTbfXCj/lolo2HmWg3u64Behe3MNEuIYD2KWwGn5duUCbFVrtzCuzDqiwTzmwmfRwMPES5dUQTPgr5io8OQ476TzWQDs+Z6MPq2K+BFxG6nI0b9ogSXEJY4CKKRQy4VgE894JZ6jcAuVFU7ANZh3A4xvHwGxKAPtLxig2/yBrEjw=
